spring:
  profiles:
    active: local
  application:
    name: account-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3889/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password1!
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 600000
      validation-timeout: 3000
      connection-timeout: 6000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20000
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: wjn0w0SCIikfcVCJqZjn
            client-secret: gO8uLBGVwG
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: profile,email,profile_image
            client-name: Naver

          kakao:
            client-id: 96601558669376c90bdc9df3256a92e0
            client-secret: hVmwGqI6hGXdSFSBpqSxtugzpUvzbIi1
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, gender
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            jwk-set-uri: https://openapi.naver.com/v1/nid/verify
            user-name-attribute: response

          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

---
spring:
  config:
    activate:
      on-profile: local

jwt:
  token:
    secret: ${JASYPT_PASSWORD}
    duration:
      access-token: 36000000
      refresh-token: 3600000000

non-face-auth-service:
  service:
    name: "nonFaceAuthService"